Fix ninja build warning and remove unneeded head files
===>
../codec/encoder/core/loongarch/sample_lasx.c: In function ‘WelsIntra8x8Combined3Sad_lasx’:
../codec/encoder/core/loongarch/sample_lasx.c:62:14: warning: implicit declaration of function
‘WelsSampleSad8x8_lasx’; did you mean ‘WelsSampleSad8x8_c’? [-Wimplicit-function-declaration]
   iCurCost = WelsSampleSad8x8_lasx(pDstChroma, 8, pEncCb, iEncStride);
              ^~~~~~~~~~~~~~~~~~~~~
              WelsSampleSad8x8_c
<===

(1) WelsSampleSad8x8_lasx called in .c file but wrapped by #if defined(HAVE_LASX) in sad_common.h,
    so need to add HAVE_LASX define for .c files.
(2) lsx/lasx simd codes are in .c files, so there is no need to add -mlsx/-mlasx for .cpp files.