codec/common/inc/asmdefs_mmi.h: fix mips32 build
Fix the following build failure on mips32 which is raised since version
2.0.0 and
https://github.com/cisco/openh264/commit/b13e5bceb18ebb93d0313b46aab4af6f480ca933:

codec/common/mips/copy_mb_mmi.c: In function 'WelsCopy16x16_mmi':
./codec/common/inc/asmdefs_mmi.h:293:21: error: '_ABI64' undeclared (first use in this function)
  293 |    if (_MIPS_SIM == _ABI64)                                    \
      |                     ^~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/cba3e9d0fd061cc3a92cb732bcdc2c7b66dbf6cb

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>